{
 "title": "Cisco Switch RV325 Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Device OS Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hardware serial number",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "application": { "filter": "Inventory" },
     "group": { "filter": "Cisco Switch" },
     "host": { "filter": "RV325 Cisco Router" },
     "item": { "filter": "Hardware serial number" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Hardware serial number",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "application": { "filter": "Inventory" },
     "group": { "filter": "Cisco Switch" },
     "host": { "filter": "RV325 Cisco Router" },
     "item": { "filter": "Hardware serial number" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Device description",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "Cisco Switch" },
     "host": { "filter": "RV325 Cisco Router" },
     "item": { "filter": "Device description" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Traffic and Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Bits Received Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "Cisco Switch" },
     "host": { "filter": "RV325 Cisco Router" },
     "item": { "filter": "/Bits received/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Bits Sent Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "Cisco Switch" },
     "host": { "filter": "RV325 Cisco Router" },
     "item": { "filter": "/Bits sent/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Speed Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "Cisco Switch" },
     "host": { "filter": "RV325 Cisco Router" },
     "item": { "filter": "/Speed/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}