{
 "title": "ESXi SNMP Dashboard old",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Web checking" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "ESXi SNMP - 192.168.125.11" },
     "item": {
      "filter": "Download speed for scenario \"ESXi Web Client\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Web checking" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "ESXi SNMP - 192.168.125.10" },
     "item": {
      "filter": "Download speed for scenario \"ESXi Web Client\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VSAN Storage Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "ESXi SNMP - 192.168.125.10" },
     "item": { "filter": "SNMP availability" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Storage Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "title": "Local Storage utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "ESXi SNMP - 192.168.125.10" },
     "item": {
      "filter": "/vmfs/volumes/5d0f3646-73ebc416-4f95-782bcb0a7e6c: Storage utilization"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Local  Storage Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "ESXi SNMP - 192.168.125.10" },
     "item": {
      "filter": "/vmfs/volumes/5d0f3646-73ebc416-4f95-782bcb0a7e6c: Total space"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Local Storage Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 9 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "ESXi SNMP - 192.168.125.10" },
     "item": {
      "filter": "/vmfs/volumes/5d0f3646-73ebc416-4f95-782bcb0a7e6c: Used space"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VSAN Storage utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "ESXi SNMP - 192.168.125.10" },
     "item": {
      "filter": "/vmfs/volumes/vsan:52b9e3e6f92f3963-3742c70eb9987e5f: Storage utilization"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VSAN Storage Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 13 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "ESXi SNMP - 192.168.125.10" },
     "item": {
      "filter": "/vmfs/volumes/vsan:52b9e3e6f92f3963-3742c70eb9987e5f: Total space"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VSAN Storage Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 13 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "ESXi SNMP - 192.168.125.10" },
     "item": {
      "filter": "/vmfs/volumes/vsan:52b9e3e6f92f3963-3742c70eb9987e5f: Used space"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Traffic Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface Avi Internal(vSwitch0) Traffic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface Avi Internal(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface Avi Internal(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "ESXi SNMP - 192.168.125.10" },
       "item": {
        "filter": "Interface Avi Internal(vSwitch0): Bits received"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface Avi Internal(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface Avi Internal(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "ESXi SNMP - 192.168.125.10" },
       "item": {
        "filter": "Interface Avi Internal(vSwitch0): Bits sent"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interface VM Network(vSwitch0)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface Avi Internal(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface Avi Internal(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "ESXi SNMP - 192.168.125.10" },
       "item": {
        "filter": "Interface VM Network(vSwitch0): Bits received"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface Avi Internal(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface Avi Internal(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "ESXi SNMP - 192.168.125.10" },
       "item": {
        "filter": "Interface VM Network(vSwitch0): Bits sent"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interface esxi-management(vSwitch0)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface Avi Internal(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface Avi Internal(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "ESXi SNMP - 192.168.125.10" },
       "item": {
        "filter": "Interface esxi-management(vSwitch0): Bits received"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface Avi Internal(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface Avi Internal(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "ESXi SNMP - 192.168.125.10" },
       "item": {
        "filter": "Interface esxi-management(vSwitch0): Bits sent"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interface vmk1(vmk1-)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface Avi Internal(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface Avi Internal(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "ESXi SNMP - 192.168.125.10" },
       "item": {
        "filter": "Interface vmk1(vmk1-): Bits received"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface Avi Internal(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface Avi Internal(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "ESXi SNMP - 192.168.125.10" },
       "item": {
        "filter": "Interface vmk1(vmk1-): Bits sent"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}