{
 "title": "ESXi Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Group", "label": "Group", "query": "iDrac SNMP" },
   { "name": "Host", "label": "iDrac SNMP", "query": "{$Group}{*}" }
  ]
 },
 "panels": [
  {
   "title": "Interface Avi Internal(vSwitch0): Bits received Tranding",
   "type": "btplc-trend-box-panel",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "format": "decbytes",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "ESXi SNMP" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Interface Avi Internal(vSwitch0): Bits received"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Interface Avi Internal(vSwitch0): Bits sent",
   "type": "btplc-trend-box-panel",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 0 },
   "format": "decbytes",
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "ESXi SNMP" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Interface Avi Internal(vSwitch0): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Response code",
   "type": "btplc-status-dot-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "format": "none",
   "targets": [
    {
     "application": { "filter": "Web checking" },
     "group": { "filter": "ESXi SNMP" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Response code for step \"ESXi Web Client URL\" of scenario \"ESXi Web Client\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Storage Metrics - $Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  { "title": "Clock", "type": "grafana-clock-panel", "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 } },
  {
   "title": "Local Storage utilization %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/^((?!vsan).)*.Storage utilization/"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Local Storage Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/^((?!vsan).)*.Total space/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Local Storage Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/^((?!vsan).)*.Used space/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VSAN Storage utilization %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/vsan.*Storage utilization/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VSAN Storage Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 12 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/vsan.*Total space/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VSAN Storage Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 12 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "iDrac SNMP" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/vsan.*Used space/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Web Monitoring Metrics - $Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed step of scenario ESXi URL",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Web checking" },
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "Failed step of scenario \"ESXi Web Client\"."
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Response code for step  ESXi URL",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 7, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Web checking" },
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "ESXi SNMP - 192.168.125.10" },
       "item": {
        "filter": "Response code for step \"ESXi Web Client URL\" of scenario \"ESXi Web Client\"."
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Failed step of scenario  ESXi URL",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "Web checking" },
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "Failed step of scenario \"ESXi Web Client\"."
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Response code  ESXi URL",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "application": { "filter": "Web checking" },
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "Response code for step \"ESXi Web Client URL\" of scenario \"ESXi Web Client\"."
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Response time ESXi URL",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "application": { "filter": "Web checking" },
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "Response time for step \"ESXi Web Client URL\" of scenario \"ESXi Web Client\"."
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Download speed  ESXi URL",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "application": { "filter": "Web checking" },
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "Download speed for step \"ESXi Web Client URL\" of scenario \"ESXi Web Client\"."
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Traffic - $Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface Avi Internal(vSwitch0) Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface Avi Internal(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface Avi Internal(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "Interface Avi Internal(vSwitch0): Bits received"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface Avi Internal(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface Avi Internal(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "ESXi SNMP - 192.168.125.10" },
       "item": {
        "filter": "Interface Avi Internal(vSwitch0): Bits sent"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Interface external(vSwitch0) Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface external(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface external(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "Interface external(vSwitch0): Bits received"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface external(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface external(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "Interface external(vSwitch0): Bits sent"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Bits Received Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface external(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface external(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/Bits received/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Bits Sent Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "application": { "filter": "Network interfaces" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "Interface external(vSwitch0):",
          " "
         ],
         "text": "replaceAlias(Interface external(vSwitch0):,  )"
        }
       ],
       "group": { "filter": "iDrac SNMP" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/Bits sent/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}