{
 "title": "VMware VMs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Group", "label": "Group", "query": "Virtual machines" },
   { "name": "Host", "label": "Virtual Machine", "query": "{$Group}{*}" }
  ]
 },
 "panels": [
  {
   "title": "vCPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Number of virtual CPUs" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Uptime" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Power state",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Power state" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU ready",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "CPU ready" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "CPU usage" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "ESXi name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "General" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Hypervisor name" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "CPU usage" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU ready",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "CPU ready" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/memory usage/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Memory size" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Network I/O (packets)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/Number of packets/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Network I/O (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Interfaces" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/Number of bytes/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Committed Storage Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Storage" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Committed storage space" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Disk Space (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/percentage/" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Space (GB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "Free disk space on ",
        " "
       ],
       "text": "replaceAlias(Free disk space on ,  )"
      }
     ],
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/Free.*((\\/)|(\\/boot)|(\\\\))$/"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk I/O (number)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Disks" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "/Average number of [reads|writes]/"
     },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk I/O (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Disks" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Host" },
     "item": { "filter": "/Average number of bytes/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Triggers",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": {
    "0": {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "proxy": { "filter": "" },
     "refId": "A",
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    "NMS3": {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    "Zabbix": {
     "application": { "filter": "/.*/" },
     "group": { "filter": "Virtual machines" },
     "host": { "filter": "$Host" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "/.*/" }
    }
   }
  }
 ]
}