{
 "title": "VSAN Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "VSAN Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "VSAN Storage Used",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Capacity" },
       "functions": [
        {
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "capacity.capacity_global.usedCapacityB",
          "Used"
         ],
         "text": "replaceAlias(capacity.capacity_global.usedCapacityB, Used)"
        }
       ],
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_global.usedCapacityB"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Capacity" },
       "functions": [
        {
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "capacity.capacity_global.freeCapacityB",
          "Free"
         ],
         "text": "replaceAlias(capacity.capacity_global.freeCapacityB, Free)"
        }
       ],
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_global.freeCapacityB"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "VSAN Storage Used %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 5, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "application": { "filter": "Capacity" },
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_global.usedpercentageCapacityB"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "VSAN Storage Used and Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 11, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "application": { "filter": "Capacity" },
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_global.usedCapacityB"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Capacity" },
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_global.totalCapacityB"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Free VSAN Storage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "application": { "filter": "Capacity" },
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_global.freeCapacityB"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "VSAN Capacity Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Capacity" },
       "functions": [
        {
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "capacity_namespace.",
          "Capacity NameSpace "
         ],
         "text": "replaceAlias(capacity_namespace., Capacity NameSpace )"
        },
        {
         "added": false,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "capacity.",
          " "
         ],
         "text": "replaceAlias(capacity.,  )"
        }
       ],
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": { "filter": "/capacity.capacity_namespace/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "VSAN Capacity FileSystem Overhead",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "Capacity" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "capacity_fileSystemOverhead",
          "Capacity FileSystem Overhead"
         ],
         "text": "replaceAlias(capacity_fileSystemOverhead, Capacity FileSystem Overhead)"
        },
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "capacity.",
          " "
         ],
         "text": "replaceAlias(capacity.,  )"
        }
       ],
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "/capacity.capacity_fileSystemOverhead/"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  {
   "title": "VSAN Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Physical Disks Health",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Health Status" },
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": { "filter": "health.health_physicaldisks" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Cluster Health",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "Health Status" },
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": { "filter": "health.health_cluster" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Data Health",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Health Status" },
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": { "filter": "health.health_data" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "HCL Health",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "Health Status" },
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": { "filter": "health.health_hcl" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "VUM Health",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "Health Status" },
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": { "filter": "health.health_vum" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Perfvc Health",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "Health Status" },
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": { "filter": "health.health_perfsvc" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Network Health",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Health Status" },
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": { "filter": "health.health_network" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Limits Health",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "Health Status" },
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": { "filter": "health.health_limits" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  { "title": "VSAN Capacity Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Used Percentage",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Capacity" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "vsan_free" ],
       "text": "setAlias(vsan_free)"
      }
     ],
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_global.freeCapacityB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Capacity" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "vsan_total" ],
       "text": "setAlias(vsan_total)"
      }
     ],
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_global.totalCapacityB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Capacity" },
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_global.totalCapacityB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Capacity" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "vsan_free" ],
       "text": "setAlias(vsan_free)"
      }
     ],
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_global.freeCapacityB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Capacity" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "vsan_total" ],
       "text": "setAlias(vsan_total)"
      }
     ],
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_global.totalCapacityB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Primary CapacityB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Capacity" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "vsan_free" ],
       "text": "setAlias(vsan_free)"
      }
     ],
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_summary.primaryCapacityB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "OverheadB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Capacity" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "vsan_free" ],
       "text": "setAlias(vsan_free)"
      }
     ],
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_summary.overheadB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Over ReservedB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Capacity" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "vsan_free" ],
       "text": "setAlias(vsan_free)"
      }
     ],
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_summary.overReservedB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Provision CapacityB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Capacity" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "vsan_free" ],
       "text": "setAlias(vsan_free)"
      }
     ],
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_summary.provisionCapacityB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Reserved CapacityB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Capacity" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "vsan_free" ],
       "text": "setAlias(vsan_free)"
      }
     ],
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_summary.reservedCapacityB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Capacity" },
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_global.freeCapacityB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "UsedB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Capacity" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "vsan_free" ],
       "text": "setAlias(vsan_free)"
      }
     ],
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_summary.usedB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Physical UsedB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Capacity" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "vsan_free" ],
       "text": "setAlias(vsan_free)"
      }
     ],
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_summary.physicalUsedB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Temporary OverheadB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Capacity" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "vsan_free" ],
       "text": "setAlias(vsan_free)"
      }
     ],
     "group": { "filter": "VSAN" },
     "host": { "filter": "vsanDatastore" },
     "item": {
      "filter": "capacity.capacity_summary.temporaryOverheadB"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "VSAN Efficient Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ratio",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Capacity" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "vsan_free" ],
         "text": "setAlias(vsan_free)"
        }
       ],
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_efficientcapacity.ratio"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Deduplication Meta Data Size",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 2, "y": 12 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "Capacity" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "vsan_free" ],
         "text": "setAlias(vsan_free)"
        }
       ],
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_efficientcapacity.dedupMetadataSize"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Logical Used %",
     "type": "blackmirror1-singlestat-math-panel",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 12 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "Capacity" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "logical_total" ],
         "text": "setAlias(logical_total)"
        }
       ],
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_efficientcapacity.physicalCapacity"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Capacity" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "logical_used" ],
         "text": "setAlias(logical_used)"
        }
       ],
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_efficientcapacity.logicalCapacityUsed"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Physical Capacity",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 12 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "Capacity" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "vsan_free" ],
         "text": "setAlias(vsan_free)"
        }
       ],
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_efficientcapacity.physicalCapacity"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Logical Capacity",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 12 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "Capacity" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "vsan_free" ],
         "text": "setAlias(vsan_free)"
        }
       ],
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_efficientcapacity.logicalCapacity"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Physical Capacity Used %",
     "type": "blackmirror1-singlestat-math-panel",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "Capacity" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "total" ],
         "text": "setAlias(total)"
        }
       ],
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_efficientcapacity.physicalCapacity"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Capacity" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "used" ],
         "text": "setAlias(used)"
        }
       ],
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": {
        "filter": "capacity.capacity_efficientcapacity.physicalCapacityUsed"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Physical Capacity Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "application": { "filter": "Capacity" },
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "vsan_free" ],
         "text": "setAlias(vsan_free)"
        }
       ],
       "group": { "filter": "VSAN" },
       "host": { "filter": "vsanDatastore" },
       "item": { "filter": "capacity" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}